source 'https://rubygems.org'

gem 'roda', '~> 3.19'
gem 'sqlite3', '~> 1.4', '>= 1.4.1'
gem 'sequel', '~> 5.20'
# gem 'rack-unreloader', '~> 1.7', :require => 'rack/unreloader'
gem 'thin', '~> 1.7', '>= 1.7.2'
gem 'bcrypt', '~> 3.1', '>= 3.1.12'
gem 'jwt', '~> 2.1'
gem 'rack-protection', '~> 2.0', '>= 2.0.5', :require => 'rack/protection'